package me.gaigeshen.mybatis.helper.spring;

import org.hsqldb.jdbc.JDBCDataSource;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 * Demo configuration, see TestCase class
 *
 * @author gaigeshen
 */
@MapperScan("me.gaigeshen.mybatis.helper.spring.mapper")
@Configuration
public class MybatisHelperConfiguration {

  // Replace SqlSessionFactoryBean to MybatisHelperSqlSessionFactoryBean
  // to enable mybatis-helper-spring features
  @Bean
  public MybatisHelperSqlSessionFactoryBean mybatisHelperSqlSessionFactoryBean() throws Exception {
    MybatisHelperSqlSessionFactoryBean factoryBean = new MybatisHelperSqlSessionFactoryBean();
    factoryBean.setDataSource(dataSource());

    org.apache.ibatis.session.Configuration cfg = new org.apache.ibatis.session.Configuration();
    cfg.setUseGeneratedKeys(true);
    factoryBean.setConfiguration(cfg);

    return factoryBean;
  }

  @Bean
  public DataSource dataSource() throws Exception {
    JDBCDataSource dataSource = new JDBCDataSource();
    dataSource.setUrl("jdbc:hsqldb:mem:testdb");
    dataSource.setUser("SA");
    dataSource.setPassword("");
    initializeDatabase(dataSource);
    return dataSource;
  }

  // 初始化测试数据库表
  private void initializeDatabase(DataSource dataSource) throws Exception {
    Connection connection = dataSource.getConnection();
    connection.setAutoCommit(false);
    PreparedStatement statement = connection.prepareStatement(
            "create table user (" +
                    "identity bigint generated by default as identity (start with 1, increment by 1) primary key," +
                    "username varchar(255));");
    statement.execute();
    connection.commit();
  }

}
